#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_FOCALTECH_FINGERPRINT) += focaltech/

obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208) += goodix/
obj-$(CONFIG_FINGERPRINT_FPC1020) += fpc/

